# Generated by Django 2.2 on 2019-05-12 15:26

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("package", "0004_auto_20180214_0617")]

    operations = [
        migrations.AddField(model_name="version", name="encoded_readme", field=models.TextField(blank=True, null=True)),
        migrations.AddField(model_name="version", name="readme", field=models.TextField(blank=True, null=True)),
        migrations.AlterField(
            model_name="package",
            name="repo_url",
            field=models.URLField(
                blank=True,
                help_text="Enter your project repo hosting URL here. Example: https://github.com/martin-jahn/elm-finder",
                unique=True,
                verbose_name="repo URL",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="package.Package",
            ),
        ),
        migrations.AlterUniqueTogether(name="version", unique_together={("package", "number")}),
        migrations.CreateModel(
            name="Doc",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("encoded_content", django.contrib.postgres.fields.jsonb.JSONField()),
                ("order", models.IntegerField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="docs", to="package.Version"
                    ),
                ),
            ],
            options={"unique_together": {("version", "order")}},
        ),
    ]
